name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_JSON_KEY }}

      - name: Build and push Docker image
        env:
          MONGO_URI: ${{ secrets.DB_URL }}
        run: |
          docker build --build-arg MONGO_URI=${{ secrets.DB_URL }} -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/blog-backend-0.0.1-SNAPSHOT.jar:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/blog-backend-0.0.1-SNAPSHOT.jar:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        env:
          MONGO_URI: ${{ secrets.DB_URL }}
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_JSON_KEY }}
          gcloud run deploy blog-backend-0.0.1-SNAPSHOT.jar \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/blog-backend-0.0.1-SNAPSHOT.jar:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars "JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC" \
            --set-env-vars "MONGO_URI=${{ secrets.DB_URL }}"
